#!/usr/bin/env python3
"""信封契约文档生成器（W2 治理）——「三处手工同步」的终结。

单一权威 = `worker/src/api/envelope_contract.py`（EnvelopeExtensions 键模型 +
EXTENSION_KEY_ORIGINS）。本脚本从它生成两份产物：
  1. `api-integration/envelope-keys.json`           —— 机器可读键清单（skill 侧 parity 测试消费）
  2. `docs/CONTRACT-v4.md` 中 ENVELOPE-CONTRACT 标记块 —— 人读键表（勿手改）

用法（在 worker/ 或仓库根均可）：
    python scripts/gen_contract_docs.py            # 生成并落盘
    python scripts/gen_contract_docs.py --check    # CI 门禁：漂移即 exit 1（不落盘）

改键流程：改 envelope_contract.py（模型字段 + EXTENSION_KEY_ORIGINS + 描述）→
跑本脚本 → 提交四处变更（模型/JSON/CONTRACT 块；skill 侧测试自动跟随）。
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Optional  # noqa: F401 — 供 envelope_contract 注解解析环境兜底

SCRIPT_DIR = Path(__file__).resolve().parent
WORKER_DIR = SCRIPT_DIR.parent
REPO_ROOT = WORKER_DIR.parent
sys.path.insert(0, str(WORKER_DIR / "src"))

from api.envelope_contract import (  # noqa: E402
    EXTENSION_KEY_ORIGINS,
    EnvelopeExtensions,
)

JSON_PATH = REPO_ROOT / "api-integration" / "envelope-keys.json"
CONTRACT_PATH = REPO_ROOT / "docs" / "CONTRACT-v4.md"
BEGIN_MARKER = "<!-- ENVELOPE-CONTRACT:BEGIN（generated by worker/scripts/gen_contract_docs.py——勿手改，改 api/envelope_contract.py 后重跑本脚本） -->"
END_MARKER = "<!-- ENVELOPE-CONTRACT:END -->"


def generate_json() -> dict:
    fields = EnvelopeExtensions.model_fields
    missing_origin = sorted(set(fields) - set(EXTENSION_KEY_ORIGINS))
    extra_origin = sorted(set(EXTENSION_KEY_ORIGINS) - set(fields))
    if missing_origin or extra_origin:
        raise SystemExit(
            f"envelope_contract.py 内部不一致：模型缺来源登记 {missing_origin}；"
            f"来源表多余键 {extra_origin}——两处必须同步"
        )
    return {
        "_authority": "worker/src/api/envelope_contract.py (EnvelopeExtensions)",
        "_regenerate": "python worker/scripts/gen_contract_docs.py",
        "root_keys": ["draft", "source", "extensions", "assets"],
        "extensions": {
            key: {
                "origin": EXTENSION_KEY_ORIGINS[key],
                "description": (field.description or ""),
            }
            for key, field in fields.items()
        },
    }


def render_markdown() -> str:
    fields = EnvelopeExtensions.model_fields
    lines = [
        "### envelope extensions 键权威清单（自动生成）",
        "",
        "> 单一权威 = `worker/src/api/envelope_contract.py`（`EnvelopeExtensions` extra=\"forbid\"）。",
        "> worker 提交层/ingest 对未知键 fail-closed（`ENVELOPE_STRICT=0` 降级 warn）；",
        "> 本表由 `worker/scripts/gen_contract_docs.py` 生成——**勿手改**。legacy 键仅为存量草稿 resubmit 兼容，新代码禁用。",
        "",
        "| 键 | 来源 | 说明 |",
        "|---|---|---|",
    ]
    for key, field in fields.items():
        desc = (field.description or "").replace("|", "\\|")
        lines.append(f"| `{key}` | {EXTENSION_KEY_ORIGINS[key]} | {desc} |")
    return "\n".join(lines)


def _contract_block() -> str:
    return f"{BEGIN_MARKER}\n{render_markdown()}\n{END_MARKER}"


def _replace_contract_block(text: str) -> tuple[str, bool]:
    if BEGIN_MARKER in text and END_MARKER in text:
        pre = text.split(BEGIN_MARKER, 1)[0]
        post = text.split(END_MARKER, 1)[1]
        return pre + _contract_block() + post, True
    if BEGIN_MARKER in text or END_MARKER in text:
        raise SystemExit("CONTRACT-v4.md 标记块不完整（只有单侧标记）——请手工修复为成对标记")
    return text, False


def main() -> int:
    parser = argparse.ArgumentParser(description="信封契约文档生成器")
    parser.add_argument("--check", action="store_true", help="CI 门禁：产物与模型漂移即 exit 1")
    args = parser.parse_args()

    expected_json = json.dumps(generate_json(), ensure_ascii=False, indent=2) + "\n"
    actual_json = JSON_PATH.read_text(encoding="utf-8") if JSON_PATH.exists() else ""
    contract_text = CONTRACT_PATH.read_text(encoding="utf-8")
    expected_contract = _replace_contract_block(contract_text)[0]

    drift: list[str] = []
    if actual_json != expected_json:
        drift.append(f"api-integration/envelope-keys.json 与模型不一致")
    if expected_contract != contract_text:
        drift.append("docs/CONTRACT-v4.md 键表块与模型不一致")

    if args.check:
        if drift:
            print("❌ 信封契约文档漂移：")
            for d in drift:
                print(f"  - {d}")
            print("  修复: python worker/scripts/gen_contract_docs.py（重生成并提交）")
            return 1
        print("✅ 信封契约文档与模型零漂移")
        return 0

    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    JSON_PATH.write_text(expected_json, encoding="utf-8")
    CONTRACT_PATH.write_text(expected_contract, encoding="utf-8")
    if not _replace_contract_block(contract_text)[1]:
        print("ℹ️ CONTRACT-v4.md 原无标记块，已追加（下次 --check 起生效）")
    print(f"✅ 已生成 {JSON_PATH.relative_to(REPO_ROOT)} + CONTRACT-v4.md 键表块（{len(EnvelopeExtensions.model_fields)} 键）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
