/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBestsellersRouteImport } from './routes/_authenticated/bestsellers'
import { Route as AuthenticatedCollectBoxRouteImport } from './routes/_authenticated/collect-box'
import { Route as AuthenticatedDataScreenRouteImport } from './routes/_authenticated/data-screen'
import { Route as AuthenticatedImageStudioRouteImport } from './routes/_authenticated/image-studio'
import { Route as AuthenticatedOnSaleRouteImport } from './routes/_authenticated/on-sale'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated/stores'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBestsellersRoute =
  AuthenticatedBestsellersRouteImport.update({
    id: '/bestsellers',
    path: '/bestsellers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectBoxRoute = AuthenticatedCollectBoxRouteImport.update({
  id: '/collect-box',
  path: '/collect-box',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataScreenRoute = AuthenticatedDataScreenRouteImport.update({
  id: '/data-screen',
  path: '/data-screen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImageStudioRoute =
  AuthenticatedImageStudioRouteImport.update({
    id: '/image-studio',
    path: '/image-studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnSaleRoute = AuthenticatedOnSaleRouteImport.update({
  id: '/on-sale',
  path: '/on-sale',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bestsellers': typeof AuthenticatedBestsellersRoute
  '/collect-box': typeof AuthenticatedCollectBoxRoute
  '/data-screen': typeof AuthenticatedDataScreenRoute
  '/image-studio': typeof AuthenticatedImageStudioRoute
  '/on-sale': typeof AuthenticatedOnSaleRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bestsellers': typeof AuthenticatedBestsellersRoute
  '/collect-box': typeof AuthenticatedCollectBoxRoute
  '/data-screen': typeof AuthenticatedDataScreenRoute
  '/image-studio': typeof AuthenticatedImageStudioRoute
  '/on-sale': typeof AuthenticatedOnSaleRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bestsellers': typeof AuthenticatedBestsellersRoute
  '/_authenticated/collect-box': typeof AuthenticatedCollectBoxRoute
  '/_authenticated/data-screen': typeof AuthenticatedDataScreenRoute
  '/_authenticated/image-studio': typeof AuthenticatedImageStudioRoute
  '/_authenticated/on-sale': typeof AuthenticatedOnSaleRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/bestsellers'
    | '/collect-box'
    | '/data-screen'
    | '/image-studio'
    | '/on-sale'
    | '/orders'
    | '/pricing'
    | '/products'
    | '/settings'
    | '/stores'
    | '/tasks'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/bestsellers'
    | '/collect-box'
    | '/data-screen'
    | '/image-studio'
    | '/on-sale'
    | '/orders'
    | '/pricing'
    | '/products'
    | '/settings'
    | '/stores'
    | '/tasks'
    | '/templates'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/bestsellers'
    | '/_authenticated/collect-box'
    | '/_authenticated/data-screen'
    | '/_authenticated/image-studio'
    | '/_authenticated/on-sale'
    | '/_authenticated/orders'
    | '/_authenticated/pricing'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/_authenticated/stores'
    | '/_authenticated/tasks'
    | '/_authenticated/templates'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bestsellers': {
      id: '/_authenticated/bestsellers'
      path: '/bestsellers'
      fullPath: '/bestsellers'
      preLoaderRoute: typeof AuthenticatedBestsellersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collect-box': {
      id: '/_authenticated/collect-box'
      path: '/collect-box'
      fullPath: '/collect-box'
      preLoaderRoute: typeof AuthenticatedCollectBoxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-screen': {
      id: '/_authenticated/data-screen'
      path: '/data-screen'
      fullPath: '/data-screen'
      preLoaderRoute: typeof AuthenticatedDataScreenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/image-studio': {
      id: '/_authenticated/image-studio'
      path: '/image-studio'
      fullPath: '/image-studio'
      preLoaderRoute: typeof AuthenticatedImageStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/on-sale': {
      id: '/_authenticated/on-sale'
      path: '/on-sale'
      fullPath: '/on-sale'
      preLoaderRoute: typeof AuthenticatedOnSaleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBestsellersRoute: typeof AuthenticatedBestsellersRoute
  AuthenticatedCollectBoxRoute: typeof AuthenticatedCollectBoxRoute
  AuthenticatedDataScreenRoute: typeof AuthenticatedDataScreenRoute
  AuthenticatedImageStudioRoute: typeof AuthenticatedImageStudioRoute
  AuthenticatedOnSaleRoute: typeof AuthenticatedOnSaleRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBestsellersRoute: AuthenticatedBestsellersRoute,
  AuthenticatedCollectBoxRoute: AuthenticatedCollectBoxRoute,
  AuthenticatedDataScreenRoute: AuthenticatedDataScreenRoute,
  AuthenticatedImageStudioRoute: AuthenticatedImageStudioRoute,
  AuthenticatedOnSaleRoute: AuthenticatedOnSaleRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
